server:
  port: 8002
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/luccs/spring-cloud-demo/     # 配置git仓库的地址
          search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: luccs                                        # git仓库的账号
          password: luccs526hc                                    # git仓库的密码
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: 123456

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/   ## 注册中心eurka地址


management:
  security:
     enabled: false

